//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_magazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres_dostavki
    {
        public int id { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<int> users_id { get; set; }
        public Nullable<int> orders_id { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual users users { get; set; }
    }
}
