//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_magazin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class magazinEntities14 : DbContext
    {
        public magazinEntities14()
            : base("name=magazinEntities14")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adres_dostavki> adres_dostavki { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<support_spasibo> support_spasibo { get; set; }
        public virtual DbSet<support_zhaloba> support_zhaloba { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tovar> tovar { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
