//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_magazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class support_spasibo
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string message_user { get; set; }
        public string email_users { get; set; }
        public string user_image { get; set; }
    
        public virtual users users { get; set; }
    }
}
