//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_magazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.adres_dostavki = new HashSet<adres_dostavki>();
            this.orders = new HashSet<orders>();
            this.support_spasibo = new HashSet<support_spasibo>();
            this.support_zhaloba = new HashSet<support_zhaloba>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> number { get; set; }
        public string date_of_birthday { get; set; }
        public string gender { get; set; }
        public string login { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string image_path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adres_dostavki> adres_dostavki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<support_spasibo> support_spasibo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<support_zhaloba> support_zhaloba { get; set; }
        public bool Login(string password)
        {
            // Проверяем правильность пароля
            return this.password == password;

        }
    }
}

